const DEFAULT_EXCLUSIONS = [
    "VEHICLE",
    "FLEET",
    "BASELINE",
    "CUID",
    "SOURCE_DESCRIPTION",
    "ITEMS_GROUP",
    "EVENT_IDA",
    "SHORT_NAME",
    "START_TIMESTAMP",
    "END_TIMESTAMP"
];
